language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=4.1
    - BASE_IMAGE_STABILITY_TAG=2.4.0
  matrix:
    - VARNISH_VER=4.1 TAG=4.1 EXTRA_TAG=4

script:
  - cd ./"${VARNISH_VER:0:1}"
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
